name: Validate Markers
on:
  push:
  pull_request:

permissions: {}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check markers exist
        run: |
          grep -q "<!-- RECENT_ACTIVITY:START -->" README.md
          grep -q "<!-- RECENT_ACTIVITY:END -->" README.md
